version: '3.2'

networks:
  backend-network:
    driver: bridge
  web-projects:
    external:
       name: ${EXTERNAL_NETWORK_NAME}

services:
  # Nextjs applicaton container
  &app-service app: &app-service-template
    image: node:10.17-alpine
    user: ${UID}:${GID}
    volumes:
      - ./src:/app:rw
    container_name: ${VIRTUAL_HOST}-app
    restart: on-failure
    working_dir: "/app"
    command: ["yarn", "dev"]
    ports: ["${PORT}:${PORT}"]
    networks:
      - backend-network
      - web-projects

  # NGINX container for PHP-FPM with Yii2 Administrative panel
  &web-service nginx-app:
    build:
      context: ./docker/nginx-1.16
      dockerfile: Dockerfile
    restart: on-failure
    container_name: ${VIRTUAL_HOST}-web
    environment:
      NODE_HOST: ${VIRTUAL_HOST}-app
      NODE_PORT: "${PORT}"
      ROOT_DIR: '/app'
      VIRTUAL_HOST: "${VIRTUAL_HOST}"
      LETSENCRYPT_HOST: "${VIRTUAL_HOST}"
    volumes:
      - ./src:/app:ro
#    ports: ['9991:80']
    depends_on:
      - *app-service
    networks:
      - web-projects

  # Node.js container with NPM & Yarn & Gulp TODO. Нужно не запускать при общем up
  &node-service node:
    build:
      context: ./docker/node-10.17
      dockerfile: Dockerfile
    user: ${UID}:${GID}
    volumes:
      - ./src:/app:rw
    restart: no
    depends_on: []
    networks:
      - backend-network