version: '3.2'

networks:
  backend-network:
    driver: bridge
  web-projects:
    external:
       name: ${EXTERNAL_NETWORK_NAME}

services:
  # Nextjs applicaton container
  &app-service app: &app-service-template
    image: node:10.17-alpine
    user: ${UID}:${GID}
    volumes:
      - ./src:/app:rw
    container_name: ${VIRTUAL_HOST}-app
    restart: on-failure
    working_dir: "/app"
    ports: ["${PORT}:${PORT}"]
    networks:
      - backend-network
      - web-projects

  # NGINX container with proxy
  &web-service nginx-app:
    build:
      context: ./docker/nginx-proxy-1.16
      dockerfile: Dockerfile
    restart: on-failure
    container_name: ${VIRTUAL_HOST}-web
    environment:
      REMOTE_HOST: ${VIRTUAL_HOST}-app
      REMOTE_PORT: "${PORT}"
      ROOT_DIR: '/app'
      VIRTUAL_HOST: "${VIRTUAL_HOST}"
      LETSENCRYPT_HOST: "${VIRTUAL_HOST}"
    volumes:
      - ./src:/app:ro
#    ports: ['9991:80']
    networks:
      - web-projects