version: "3.5"

networks:
  backend-network:
    external:
      name: "${BACKEND_NETWORK_NAME}"

services:
  # Nextjs applicaton container
  &app-service node: &app-service-template
    image: node:12-alpine
    logging:
      driver: "json-file"
      options:
        max-file: "2"
        max-size: "5m"
    environment: &app-service-envs
      API_URL: "${API_URL}"
      NEXT_TELEMETRY_DISABLED: "${NEXT_TELEMETRY_DISABLED}"
    working_dir: "/app"
    volumes:
      - ./../../src:/app:rw
    networks:
      - backend-network