version: "3.5"

networks:
  frontend-network:
    external:
      name: "${FRONTEND_NETWORK_NAME}"
  backend-network:
    external:
      name: "${BACKEND_NETWORK_NAME}"

services:
  # Nextjs applicaton container
  &app-service app:
    image: node:12-alpine
    logging:
      driver: "json-file"
      options:
        max-file: "2"
        max-size: "5m"
    container_name: ${COMPOSE_PROJECT_NAME}-app
    restart: always
    environment:
      API_URL: "${API_URL}"
      NEXT_TELEMETRY_DISABLED: "${NEXT_TELEMETRY_DISABLED}"
      PORT: &nodejs-port 3000
    command: ["yarn", "start"]
    working_dir: "/app"
    volumes:
      - ./../../src:/app:rw
    networks:
      - backend-network

  # NGINX container with proxy
  nginx-app:
    image: git.chulakov.org:5555/docker/compose/images/nginx:1.17-1.0.0-proxy
    logging:
      driver: "json-file"
      options:
        max-file: "2"
        max-size: "5m"
    container_name: ${COMPOSE_PROJECT_NAME}-nginx
    restart: always
    depends_on:
      - *app-service
    environment:
      REMOTE_HOST: ${COMPOSE_PROJECT_NAME}-app
      REMOTE_PORT: *nodejs-port
      ROOT_DIR: "/app"
      VIRTUAL_HOST: "${COMPOSE_PROJECT_NAME}"
      LETSENCRYPT_HOST: "${COMPOSE_PROJECT_NAME}"
    volumes:
      - ./../../src:/app:ro
    networks:
      - backend-network
      - frontend-network